/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as OahuCommuteRouteImport } from './routes/oahu-commute'
import { Route as ApiPublicImportGtfsRouteImport } from './routes/api/public/import-gtfs'
import { Route as ApiPublicPushDispatchRouteImport } from './routes/api/public/push-dispatch'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const OahuCommuteRoute = OahuCommuteRouteImport.update({
  id: '/oahu-commute',
  path: '/oahu-commute',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicImportGtfsRoute = ApiPublicImportGtfsRouteImport.update({
  id: '/api/public/import-gtfs',
  path: '/api/public/import-gtfs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPushDispatchRoute = ApiPublicPushDispatchRouteImport.update({
  id: '/api/public/push-dispatch',
  path: '/api/public/push-dispatch',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/reset-password': typeof ResetPasswordRoute
  '/welcome': typeof WelcomeRoute
  '/oahu-commute': typeof OahuCommuteRoute
  '/api/public/import-gtfs': typeof ApiPublicImportGtfsRoute
  '/api/public/push-dispatch': typeof ApiPublicPushDispatchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/reset-password': typeof ResetPasswordRoute
  '/welcome': typeof WelcomeRoute
  '/oahu-commute': typeof OahuCommuteRoute
  '/api/public/import-gtfs': typeof ApiPublicImportGtfsRoute
  '/api/public/push-dispatch': typeof ApiPublicPushDispatchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/reset-password': typeof ResetPasswordRoute
  '/welcome': typeof WelcomeRoute
  '/oahu-commute': typeof OahuCommuteRoute
  '/api/public/import-gtfs': typeof ApiPublicImportGtfsRoute
  '/api/public/push-dispatch': typeof ApiPublicPushDispatchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/reset-password'
    | '/welcome'
    | '/oahu-commute'
    | '/api/public/import-gtfs'
    | '/api/public/push-dispatch'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/reset-password'
    | '/welcome'
    | '/oahu-commute'
    | '/api/public/import-gtfs'
    | '/api/public/push-dispatch'
  id:
    | '__root__'
    | '/'
    | '/reset-password'
    | '/welcome'
    | '/oahu-commute'
    | '/api/public/import-gtfs'
    | '/api/public/push-dispatch'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  WelcomeRoute: typeof WelcomeRoute
  OahuCommuteRoute: typeof OahuCommuteRoute
  ApiPublicImportGtfsRoute: typeof ApiPublicImportGtfsRoute
  ApiPublicPushDispatchRoute: typeof ApiPublicPushDispatchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oahu-commute': {
      id: '/oahu-commute'
      path: '/oahu-commute'
      fullPath: '/oahu-commute'
      preLoaderRoute: typeof OahuCommuteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/import-gtfs': {
      id: '/api/public/import-gtfs'
      path: '/api/public/import-gtfs'
      fullPath: '/api/public/import-gtfs'
      preLoaderRoute: typeof ApiPublicImportGtfsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/push-dispatch': {
      id: '/api/public/push-dispatch'
      path: '/api/public/push-dispatch'
      fullPath: '/api/public/push-dispatch'
      preLoaderRoute: typeof ApiPublicPushDispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  WelcomeRoute: WelcomeRoute,
  OahuCommuteRoute: OahuCommuteRoute,
  ApiPublicImportGtfsRoute: ApiPublicImportGtfsRoute,
  ApiPublicPushDispatchRoute: ApiPublicPushDispatchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
