/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as InstallRouteImport } from './routes/install'
import { Route as OahuCommuteRouteImport } from './routes/oahu-commute'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as ApiPublicHealthRouteImport } from './routes/api/public/health'
import { Route as ApiPublicImportGtfsRouteImport } from './routes/api/public/import-gtfs'
import { Route as ApiPublicLeaveAlertsRouteImport } from './routes/api/public/leave-alerts'
import { Route as ApiPublicPushDispatchRouteImport } from './routes/api/public/push-dispatch'
import { Route as ApiPublicUnsubscribeRouteImport } from './routes/api/public/unsubscribe'
import { Route as ApiPublicVersionRouteImport } from './routes/api/public/version'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallRoute = InstallRouteImport.update({
  id: '/install',
  path: '/install',
  getParentRoute: () => rootRouteImport,
} as any)
const OahuCommuteRoute = OahuCommuteRouteImport.update({
  id: '/oahu-commute',
  path: '/oahu-commute',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/api/public/health',
  path: '/api/public/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicImportGtfsRoute = ApiPublicImportGtfsRouteImport.update({
  id: '/api/public/import-gtfs',
  path: '/api/public/import-gtfs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLeaveAlertsRoute = ApiPublicLeaveAlertsRouteImport.update({
  id: '/api/public/leave-alerts',
  path: '/api/public/leave-alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPushDispatchRoute = ApiPublicPushDispatchRouteImport.update({
  id: '/api/public/push-dispatch',
  path: '/api/public/push-dispatch',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicUnsubscribeRoute = ApiPublicUnsubscribeRouteImport.update({
  id: '/api/public/unsubscribe',
  path: '/api/public/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicVersionRoute = ApiPublicVersionRouteImport.update({
  id: '/api/public/version',
  path: '/api/public/version',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/disclaimer': typeof DisclaimerRoute
  '/install': typeof InstallRoute
  '/oahu-commute': typeof OahuCommuteRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/welcome': typeof WelcomeRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/import-gtfs': typeof ApiPublicImportGtfsRoute
  '/api/public/leave-alerts': typeof ApiPublicLeaveAlertsRoute
  '/api/public/push-dispatch': typeof ApiPublicPushDispatchRoute
  '/api/public/unsubscribe': typeof ApiPublicUnsubscribeRoute
  '/api/public/version': typeof ApiPublicVersionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/disclaimer': typeof DisclaimerRoute
  '/install': typeof InstallRoute
  '/oahu-commute': typeof OahuCommuteRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/welcome': typeof WelcomeRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/import-gtfs': typeof ApiPublicImportGtfsRoute
  '/api/public/leave-alerts': typeof ApiPublicLeaveAlertsRoute
  '/api/public/push-dispatch': typeof ApiPublicPushDispatchRoute
  '/api/public/unsubscribe': typeof ApiPublicUnsubscribeRoute
  '/api/public/version': typeof ApiPublicVersionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/disclaimer': typeof DisclaimerRoute
  '/install': typeof InstallRoute
  '/oahu-commute': typeof OahuCommuteRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/welcome': typeof WelcomeRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/import-gtfs': typeof ApiPublicImportGtfsRoute
  '/api/public/leave-alerts': typeof ApiPublicLeaveAlertsRoute
  '/api/public/push-dispatch': typeof ApiPublicPushDispatchRoute
  '/api/public/unsubscribe': typeof ApiPublicUnsubscribeRoute
  '/api/public/version': typeof ApiPublicVersionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/disclaimer'
    | '/install'
    | '/oahu-commute'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/welcome'
    | '/api/public/health'
    | '/api/public/import-gtfs'
    | '/api/public/leave-alerts'
    | '/api/public/push-dispatch'
    | '/api/public/unsubscribe'
    | '/api/public/version'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/disclaimer'
    | '/install'
    | '/oahu-commute'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/welcome'
    | '/api/public/health'
    | '/api/public/import-gtfs'
    | '/api/public/leave-alerts'
    | '/api/public/push-dispatch'
    | '/api/public/unsubscribe'
    | '/api/public/version'
  id:
    | '__root__'
    | '/'
    | '/disclaimer'
    | '/install'
    | '/oahu-commute'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/welcome'
    | '/api/public/health'
    | '/api/public/import-gtfs'
    | '/api/public/leave-alerts'
    | '/api/public/push-dispatch'
    | '/api/public/unsubscribe'
    | '/api/public/version'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DisclaimerRoute: typeof DisclaimerRoute
  InstallRoute: typeof InstallRoute
  OahuCommuteRoute: typeof OahuCommuteRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermsRoute: typeof TermsRoute
  WelcomeRoute: typeof WelcomeRoute
  ApiPublicHealthRoute: typeof ApiPublicHealthRoute
  ApiPublicImportGtfsRoute: typeof ApiPublicImportGtfsRoute
  ApiPublicLeaveAlertsRoute: typeof ApiPublicLeaveAlertsRoute
  ApiPublicPushDispatchRoute: typeof ApiPublicPushDispatchRoute
  ApiPublicUnsubscribeRoute: typeof ApiPublicUnsubscribeRoute
  ApiPublicVersionRoute: typeof ApiPublicVersionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/install': {
      id: '/install'
      path: '/install'
      fullPath: '/install'
      preLoaderRoute: typeof InstallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oahu-commute': {
      id: '/oahu-commute'
      path: '/oahu-commute'
      fullPath: '/oahu-commute'
      preLoaderRoute: typeof OahuCommuteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/health': {
      id: '/api/public/health'
      path: '/api/public/health'
      fullPath: '/api/public/health'
      preLoaderRoute: typeof ApiPublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/import-gtfs': {
      id: '/api/public/import-gtfs'
      path: '/api/public/import-gtfs'
      fullPath: '/api/public/import-gtfs'
      preLoaderRoute: typeof ApiPublicImportGtfsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/leave-alerts': {
      id: '/api/public/leave-alerts'
      path: '/api/public/leave-alerts'
      fullPath: '/api/public/leave-alerts'
      preLoaderRoute: typeof ApiPublicLeaveAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/push-dispatch': {
      id: '/api/public/push-dispatch'
      path: '/api/public/push-dispatch'
      fullPath: '/api/public/push-dispatch'
      preLoaderRoute: typeof ApiPublicPushDispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/unsubscribe': {
      id: '/api/public/unsubscribe'
      path: '/api/public/unsubscribe'
      fullPath: '/api/public/unsubscribe'
      preLoaderRoute: typeof ApiPublicUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/version': {
      id: '/api/public/version'
      path: '/api/public/version'
      fullPath: '/api/public/version'
      preLoaderRoute: typeof ApiPublicVersionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DisclaimerRoute: DisclaimerRoute,
  InstallRoute: InstallRoute,
  OahuCommuteRoute: OahuCommuteRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermsRoute: TermsRoute,
  WelcomeRoute: WelcomeRoute,
  ApiPublicHealthRoute: ApiPublicHealthRoute,
  ApiPublicImportGtfsRoute: ApiPublicImportGtfsRoute,
  ApiPublicLeaveAlertsRoute: ApiPublicLeaveAlertsRoute,
  ApiPublicPushDispatchRoute: ApiPublicPushDispatchRoute,
  ApiPublicUnsubscribeRoute: ApiPublicUnsubscribeRoute,
  ApiPublicVersionRoute: ApiPublicVersionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
